#Launching the application with

- name: Launch database container
  docker_container:
    name: postgres
    image: deghostt/tp1-database:latest
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: app-network
  vars:
    ansible_python_interpreter: /usr/bin/python3


